import assert from "node:assert/strict";
import fs from "node:fs";
const java=fs.readFileSync(new URL("../app/src/main/java/com/supplace/app/SupPlaceActivity.java",import.meta.url),"utf8");
assert.ok(java.includes("private void registerDownloadReceiver()"));
assert.ok(java.includes("Intentionally empty"),"runtime download receiver must stay disabled to avoid launch crashes");
assert.ok(!java.includes("registerReceiver(downloadReceiver, filter"),"do not register the fragile runtime DownloadManager receiver");
assert.ok(java.includes("runOnUiThread(() -> handleCompletedUpdate(updateDownloadId))"),"WebView bridge must poll the active DownloadManager job");
assert.ok(java.includes("cursor.getInt(statusColumn) != DownloadManager.STATUS_SUCCESSFUL"));
assert.ok(java.includes("Download not complete"),"polling must detect not-yet-complete downloads without opening the installer");
assert.ok(java.includes('host.equals("github.com")'));
assert.ok(java.includes('host.endsWith(".githubusercontent.com")'));
assert.ok(java.includes("actualSha256.equals(expectedUpdateSha256)"),"APK SHA-256 must be verified before installer launch");
assert.ok(java.includes("Intent.FLAG_GRANT_READ_URI_PERMISSION"),"Package Installer must get read permission for downloaded APK");
assert.ok(java.includes("UPDATE_CHECK_TIMEOUT_MS = 10_000L"),"manual update check must have a hard 10 second watchdog");
assert.ok(java.includes("connection.setConnectTimeout(5_000)"),"GitHub connect timeout must stay short");
assert.ok(java.includes("connection.setReadTimeout(5_000)"),"GitHub read timeout must stay short");
assert.ok(java.includes("activeUpdateCheckId.compareAndSet(checkId, 0L)"),"only the first result/timeout may resolve an update check");
assert.ok(java.includes("deliverUpdateResultIfActive(checkId, result)"),"late update callbacks must be ignored");
assert.ok(java.includes("updateExecutor = Executors.newSingleThreadExecutor()"),"update checks must not block cloud RPC work");
console.log("Native updater source: polling, 10s watchdog, stale-callback guard, URL trust, SHA-256 and installer grant passed");
