import assert from "node:assert/strict";
import fs from "node:fs";
const java=fs.readFileSync(new URL("../app/src/main/java/com/supplace/app/SupPlaceActivity.java",import.meta.url),"utf8");
assert.ok(java.includes("DownloadManager.ACTION_DOWNLOAD_COMPLETE"));
assert.ok(java.includes('SuppressLint("UnspecifiedRegisterReceiverFlag")'),"system-only receiver should document the Android 14 flag exception");
assert.ok(java.includes("registerReceiver(downloadReceiver, filter);"),"DownloadManager completion must use the system-broadcast two-argument registration");
assert.ok(!java.includes("Context.RECEIVER_EXPORTED"),"do not use exported flags for the system-only completion receiver");
assert.ok(!java.includes("Context.RECEIVER_NOT_EXPORTED"),"NOT_EXPORTED can block DownloadManager completion from the system provider");
assert.ok(!java.includes("registerReceiver(downloadReceiver, filter, 0)"),"flags=0 on the three-argument overload is not the system-broadcast exemption");
assert.ok(java.includes('host.equals("github.com")'));
assert.ok(java.includes('host.endsWith(".githubusercontent.com")'));
assert.ok(java.includes("actualSha256.equals(expectedUpdateSha256)"),"APK SHA-256 must be verified before installer launch");
assert.ok(java.includes("Intent.FLAG_GRANT_READ_URI_PERMISSION"),"Package Installer must get read permission for downloaded APK");
console.log("Native updater source: system broadcast receiver, URL trust, SHA-256 and installer grant passed");
